### ISSUE TITLE
Outlook 2016 - Lesson 4 -Using Calendar View - Create Appointment in Calendar View

### ISSUE THREAD

**Issue by LeeJohnSolda** [ccidan/Office-2016#15]
Dan,
This isn't scoring still. Lee

**Comment by ccidan** [comment]
Outlook 2016 - Lesson 4 -Using Calendar View - Create Appointment in Calendar View. The problem was corrected
Is necessary a new version.

**Comment by LeeJohnSolda** [comment]
Attempted this 3 times using the Remote Office 2016 PP machine and JA version 1.1.2.4 and still scored this portion incorrectly
